version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tdev_postgres
    restart: always
    environment:
      POSTGRES_DB: toolkit
      POSTGRES_USER: toolkit_user
      POSTGRES_PASSWORD: toolkit_pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
